### ISSUE TITLE
Form validation bug

### ISSUE THREAD

**Issue by pkovzz** [SaraVieira/stop-microspending#1]
I can submit an empty form on this site: [https://stop-microspending.now.sh/](https://stop-microspending.now.sh/)
Then the following things appear.

Firstly this text:
![bug](https://user-images.githubusercontent.com/38242358/39691070-908e283c-51dc-11e8-9752-461e65d2be05.PNG)

And after a page reload, I get an infinitely loading spinner:
![loading](https://user-images.githubusercontent.com/38242358/39691120-c618eac8-51dc-11e8-9a12-43e498ee5a42.PNG)

**Comment by pkovzz** [comment]
Sorry, the env is Win10, and works in every browser.

**Comment by SaraVieira** [comment]
Fixed in the latest build at; https://stop-microspending.now.sh/


The button will keep being disabled until you fill in everything.
