### ISSUE TITLE
Should round the result because JS is being JS

### ISSUE THREAD

**Issue by Bo-Duke** [SaraVieira/stop-microspending#2]
The result should be rounded to the nearest hundredth, avoiding cases like this :
![js addition bug](https://user-images.githubusercontent.com/9383709/39691510-0f0054be-51de-11e8-8a59-3fb6c869a5e5.png)

(Yep, I'm writing 9.99 instead of 10, every penny counts :stuck_out_tongue: )

**Comment by Bo-Duke** [comment]
It can become even weirder when you throw in some annual billing :

![weirder js bug](https://user-images.githubusercontent.com/9383709/39691792-01a932b2-51df-11e8-97a5-921d6fe7c874.png)

**Comment by SaraVieira** [comment]
You sir, have a great point ! It should be fixed now if you reload the page :)

All is now rounded to two decimal points
