### ISSUE TITLE
The deployment was not found in the infrastructure layer

### ISSUE THREAD

**Issue by marktani** [SaraVieira/stop-microspending#24]
When visiting https://stop-microspending.now.sh/ I get this error:

![image](https://user-images.githubusercontent.com/1780597/67700714-c1a5b900-f9ae-11e9-9a37-e1a2dc65acb5.png)

```
Platform Error
The deployment was not found in the infrastructure layer
```

Was this deployment automatically removed by Zeit or something?

**Comment by SaraVieira** [comment]
Shit, I had no idea people used this :(

I deleted it because I was paying for v1 of zeit on it :(

**Comment by ForsakenHarmony** [comment]
https://microspending.hrmny.sh/ 🙃

**Comment by SaraVieira** [comment]
Bless you

**Comment by marktani** [comment]
amazing, thanks @ForsakenHarmony 🙌
